// respack: build-time tool that embeds an app's source directory (LuxScript
// files, templates, static assets) into a generated .cpp as byte arrays.
// Run by CMake's add_lux_desktop_app() (see CMakeLists.txt), never by hand.
//
//   respack <source-dir> <output.cpp>
//
// The generated file defines kEmbeddedFiles (include/resources.hpp): one
// entry per file, path kept relative to <source-dir> so runtime.cpp can
// recreate the exact same layout under a temp directory at startup.
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

// Anything respack itself would never need to ship: version control
// metadata and editor/OS clutter that could end up inside an app's own
// source directory. `data` is the app's RUNTIME state directory (SQLite
// database, WAL files): embedding it would make the packaged binary carry a
// stale database and the boot-time extraction overwrite the real one.
bool should_skip(const fs::path& p) {
    for (const auto& part : p) {
        const std::string s = part.string();
        if (s == ".git" || s == ".DS_Store" || s == "data") return true;
    }
    return false;
}

std::string sanitize_ident(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) out += (std::isalnum((unsigned char)c) ? c : '_');
    return out;
}

std::string escape_cpp_string(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 8);
    for (char c : s) {
        if (c == '\\' || c == '"') out += '\\';
        out += c;
    }
    return out;
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "usage: respack <source-dir> <output.cpp>\n";
        return 2;
    }
    fs::path src(argv[1]);
    fs::path out_path(argv[2]);

    if (!fs::is_directory(src)) {
        std::cerr << "respack: '" << src.string() << "' is not a directory\n";
        return 1;
    }

    std::vector<fs::path> files;
    for (const auto& entry : fs::recursive_directory_iterator(src)) {
        if (!entry.is_regular_file()) continue;
        if (should_skip(fs::relative(entry.path(), src))) continue;
        files.push_back(entry.path());
    }
    // Deterministic output: two builds of the same tree produce the same
    // generated .cpp, byte for byte.
    std::sort(files.begin(), files.end());

    fs::create_directories(out_path.parent_path());
    std::ofstream out(out_path, std::ios::binary);
    if (!out) {
        std::cerr << "respack: cannot write '" << out_path.string() << "'\n";
        return 1;
    }

    out << "// Generated by respack from " << src.string() << " -- do not edit.\n"
        << "#include \"resources.hpp\"\n\n";

    std::vector<std::string> rel_paths;
    for (size_t i = 0; i < files.size(); ++i) {
        std::ifstream in(files[i], std::ios::binary);
        std::ostringstream ss;
        ss << in.rdbuf();
        std::string bytes = ss.str();

        std::string rel = fs::relative(files[i], src).generic_string();
        rel_paths.push_back(rel);
        std::string ident = "kFile_" + std::to_string(i) + "_" + sanitize_ident(rel);

        out << "static const unsigned char " << ident << "[] = {";
        for (size_t j = 0; j < bytes.size(); ++j) {
            if (j % 20 == 0) out << "\n    ";
            out << static_cast<unsigned>(static_cast<unsigned char>(bytes[j])) << ",";
        }
        out << "\n};\n\n";
    }

    out << "const std::vector<EmbeddedFile> kEmbeddedFiles = {\n";
    for (size_t i = 0; i < files.size(); ++i) {
        std::string ident = "kFile_" + std::to_string(i) + "_" + sanitize_ident(rel_paths[i]);
        out << "    { \"" << escape_cpp_string(rel_paths[i]) << "\", " << ident
            << ", sizeof(" << ident << ") },\n";
    }
    out << "};\n";

    std::cout << "respack: embedded " << files.size() << " file(s) from "
              << src.string() << "\n";
    return 0;
}
